name: project_4
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_typeahead: ^4.8.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - .env
